$mainMod = SUPER

# Move window focus
bind = $mainMod, O, movefocus, u
bind = $mainMod, N, movefocus, l
bind = $mainMod, E, movefocus, d
bind = $mainMod, I, movefocus, r

# Resize windows
binde = $mainMod SHIFT, O, resizeactive, 0 -50
binde = $mainMod SHIFT, N, resizeactive, -50 0
binde = $mainMod SHIFT, E, resizeactive, 0 50
binde = $mainMod SHIFT, I, resizeactive, 50 0
bindm = $mainMod, mouse:273, resizewindow # NOTE: mouse:272 = right click

# Move windows
bind = $mainMod CTRL, O, movewindow, u
bind = $mainMod CTRL, N, movewindow, l
bind = $mainMod CTRL, E, movewindow, d
bind = $mainMod CTRL, I, movewindow, r
bindm = $mainMod, mouse:272, movewindow # NOTE: mouse:272 = left click

# Swap windows
bind = $mainMod CTRL SHIFT, O, swapwindow, u
bind = $mainMod CTRL SHIFT, N, swapwindow, l
bind = $mainMod CTRL SHIFT, E, swapwindow, d
bind = $mainMod CTRL SHIFT, I, swapwindow, r

# Kill window
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, forcekillactive # exec, kill $(hyprctl activewindow | grep -o 'pid: [0-9]*' | cut -d' ' -f2)

# Dwindle Layout
bind = $mainMod, H, swapsplit
bind = $mainMod, M, togglesplit
bind = $mainMod, V, pseudo

# Master Layout
bind = $mainMod, H, layoutmsg, swapwithmaster
bind = $mainMod, M, layoutmsg, addmaster
bind = $mainMod, V, layoutmsg, removemaster

# bind = $mainMod, , exec, $HOME/.config/hypr/keybinds/toggle-layout.nu # Toggle Layouts

# Grouping windows
bind = $mainMod, L, changegroupactive # change focus to another window
bind = $mainMod SHIFT, L, togglegroup # toggle group
bind = $mainMod, J, lockactivegroup, toggle # locks active group
bind = $mainMod SHIFT, J, moveoutofgroup # moves current window out of the group

# Toggle Floating Mode
bind = $mainMod, U, togglefloating, # Window
bind = $mainMod SHIFT, U, exec, hyprctl dispatch workspaceopt allfloat # Workspace

# Desktop zooming or magnifier
bind = $mainMod SHIFT, mouse_down, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"
bind = $mainMod SHIFT, mouse_up, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')" 

# Switch workspaces with mainMod
bind = $mainMod, W, workspace, 1
bind = $mainMod, C, workspace, 2
bind = $mainMod, P, workspace, 3
bind = $mainMod, B, workspace, 4
bind = $mainMod, G, workspace, 5
bind = $mainMod, K, workspace, 6
bind = $mainMod, D, workspace, 7
bind = $mainMod, F, workspace, 8
bind = $mainMod, X, workspace, 9
bind = $mainMod, Z, workspace, 10

# Move active window and follow to workspace mainMod + SHIFT
bind = $mainMod SHIFT, W, movetoworkspace, 1
bind = $mainMod SHIFT, C, movetoworkspace, 2
bind = $mainMod SHIFT, P, movetoworkspace, 3
bind = $mainMod SHIFT, B, movetoworkspace, 4
bind = $mainMod SHIFT, G, movetoworkspace, 5
bind = $mainMod SHIFT, K, movetoworkspace, 6
bind = $mainMod SHIFT, D, movetoworkspace, 7
bind = $mainMod SHIFT, F, movetoworkspace, 8
bind = $mainMod SHIFT, X, movetoworkspace, 9
bind = $mainMod SHIFT, Z, movetoworkspace, 10

# Move active window to a workspace silently mainMod + CTRL
bind = $mainMod CTRL, W, movetoworkspacesilent, 1
bind = $mainMod CTRL, C, movetoworkspacesilent, 2
bind = $mainMod CTRL, P, movetoworkspacesilent, 3
bind = $mainMod CTRL, B, movetoworkspacesilent, 4
bind = $mainMod CTRL, G, movetoworkspacesilent, 5
bind = $mainMod CTRL, K, movetoworkspacesilent, 6
bind = $mainMod CTRL, D, movetoworkspacesilent, 7
bind = $mainMod CTRL, F, movetoworkspacesilent, 8
bind = $mainMod CTRL, X, movetoworkspacesilent, 9
bind = $mainMod CTRL, Z, movetoworkspacesilent, 10
