#!/usr/bin/env bash

# This command can be used to check if any repository present in
# a specific directory are modified or not. To use this command
# cd into that specific directory and run this script

CWD=$(pwd)
DIRS=$(/usr/bin/ls -l | grep "^d" | cut -b 46-) #| sed "s/^/'/g; s/$/'/g")

for DIR in $DIRS
do
  cd $CWD/$DIR && git status | wc -l > $HOME/.cache/git-sts
  COUNT=$(cat $HOME/.cache/git-sts)
  if [[ $COUNT != "4" && $COUNT != "2" ]]; then
    pwd | bat && git status
  fi
done
