#!/usr/bin/env bash

# This command checks for git repositories present in the
# current working directory and lists their git status
# You can also pass the directory path as argument.

[ ! -z "$1" ] && cd $1
CWD=$(pwd)
DIRS=$(/usr/bin/env ls -l | grep "^d" | awk '{print $9}') #| sed "s/^/'/g; s/$/'/g")

for DIR in $DIRS
do
  cd $CWD/$DIR
  if [[ "$?" == "0" ]]; then
    COUNT=$(git status | wc -l)
    if [[ $COUNT != "4" && $COUNT != "2" ]]; then
      echo -e "\n$(tput setaf 3)$(pwd)$(tput sgr0)" && git status -s
    fi
  fi
done
