#!/usr/bin/env bash

# This command checks for git repositories present in the current working directory

CWD=$(pwd)
DIRS=$(/usr/bin/env ls -l | grep "^d" | cut -b 46-) #| sed "s/^/'/g; s/$/'/g")

for DIR in $DIRS
do
  cd $CWD/$DIR && git status | wc -l > $HOME/.cache/git-sts
  COUNT=$(cat $HOME/.cache/git-sts)
  if [[ $COUNT != "4" && $COUNT != "2" ]]; then
    pwd | bat && git status
  fi
done
