#!/usr/bin/env bash

ERROR="$(tput setaf 1)[ERROR]$(tput sgr0)"
WARN="$(tput setaf 3)[WARN]$(tput sgr0)"
INFO="$(tput setaf 4)[INFO]$(tput sgr0)"
RESET="$(tput sgr0)"
RED="$(tput setaf 1)"

function set_mail() {
  EMAIL="$(git config get --local user.email)"
  if [[ $EMAIL == "$1" ]]; then
    echo -e "${INFO} Your email is properly set (Email: \`$RED$1$RESET\`)"
  else
    if [[ ! -z $EMAIL ]]; then
      echo "${WARN} Your email is not properly set (Email: \`$RED$EMAIL$RESET\`)"
    fi
    read -n1 -rep "${WARN} Would you like to set proper email [y/n]? " INPUT
    if [[ $INPUT == "y" || $INPUT == "Y" ]]; then
      git config --local user.email $1
      echo "${INFO} Your email has been set to \`$RED$1$RESET\`"
    fi
  fi
}

MAINEMAIL="152054612+sumit-ftr@users.noreply.github.com"
TESTEMAIL="142516692+sumit-modak@users.noreply.github.com"

if [ -z "$1" ]; then
  SSHPROFILE="$(git config get --local remote.origin.url | sed -n 's/.*@\(.*\):.*/\1/p')"
  # SSHPROFILE="$(git config get --local remote.origin.url | cut -d'@' -f2 | cut -d':' -f1)"
  if [[ $SSHPROFILE == "main" ]]; then
  	set_mail $MAINEMAIL
  elif [[ $SSHPROFILE == "test" ]]; then
  	set_mail $TESTEMAIL
  else
  	echo "${ERROR} Remote \`origin\` didn't match with ssh profiles"
  fi

elif [[ "$1" == "main" ]]; then
  git config --global user.email $MAINEMAIL
  echo "${INFO} Global email changed to sumit-ftr"

elif [[ "$1" == "test" ]]; then
  git config --global user.email $TESTEMAIL
  echo "${INFO} Global email changed to sumit-modak"

else
  echo "${ERROR} SSH profile not found"
fi
