#!/usr/bin/env bash

# This script runs standalone rust programs

file="$1"
basenameNoExt=$(basename "$file" | sed "s/\.rs//g")

mkdir -p ~/.cache/rs
rustc $file -o ~/.cache/rs/$basenameNoExt && ~/.cache/rs/$basenameNoExt
rm ~/.cache/rs/$basenameNoExt 2> /dev/null
