#!/usr/bin/env bash

# This script is meant to run rust programs which is 
# not in a crate or a package and has been written as
# standalone program

file="$1"
basenameNoExt=$(basename "$file" | sed "s/\.rs//g")

clear;
rustc $file && ./$basenameNoExt; rm ./$basenameNoExt 2> /dev/null
