#!/usr/bin/env bash

# This script runs standalone rust programs

file="$1"
basenameNoExt=$(basename "$file" | sed "s/\.rs//g")

clear;
rustc $file && ./$basenameNoExt; rm ./$basenameNoExt 2> /dev/null
