#!/usr/bin/env bash

FILE="$@"
EFFECT="--transition-bezier .43,1.19,1,.4 --transition-fps 30 --transition-type grow --transition-pos 0.925,0.977 --transition-duration 2"

if [ ! -f $FILE ]; then
  echo "$FILE doesn't exist"
  exit 1
fi

swww img "$FILE" $EFFECT
wallust run -I "$FILE"

# # Get current focused monitor
# CURRENT_MONITOR=$(hyprctl monitors | awk '/^Monitor/{name=$2} /focused: yes/{print name}')
# 
# # Construct the full path to the cache file
# CACHE_FILE="$HOME/.cache/swww/$CURRENT_MONITOR"
# 
# # Check if the cache file exists for the current monitor output
# if [ -f "$CACHE_FILE" ]; then
#   # Get the wallpaper path from the cache file
#   WALLPAPER_PATH=$(grep -v 'Lanczos3' "$CACHE_FILE" | head -n 1)
# fi
