#!/usr/bin/env bash

FILE="$@"

FPS=30
TYPE=$(echo -e "any\nany\nany\nany\nfade" | shuf -n1)
DURATION=1.5
BEZIER=".43,1.19,1,.4"

EFFECT="--transition-fps $FPS --transition-type $TYPE --transition-duration $DURATION --transition-bezier $BEZIER"

if [ -f $FILE ]; then
  swww img "$FILE" $EFFECT
  wallust run -s "$FILE"
else
  echo "$FILE doesn't exist"
  exit 1
fi
