#!/usr/bin/env bash

FILE="$@"

function set_theme() {
  FPS=60
  TYPE=$(echo -e "any\nany\nany\nany\nfade" | shuf -n1)
  DURATION=1.5
  BEZIER=".43,1.19,1,.4"
  EFFECT="--transition-fps $FPS --transition-type $TYPE --transition-duration $DURATION --transition-bezier $BEZIER"

  swww img "$1" $EFFECT
  # wallust run -s "$1"
}

if [[ -f $FILE ]]; then
  set_theme "$FILE"
elif [[ $FILE == "-r" ]]; then
  # Set a random wallpaper
  set_theme "$(find ~/media/wallpapers/ -type f -regex ".*\.\(png\|jpg\|jpeg\|webp\|gif\)" | shuf -n1)"
else
  # Get current focused monitor
  CURRENT_MONITOR=$(hyprctl monitors | awk '/^Monitor/{name=$2} /focused: yes/{print name}')

  # Construct the full path to the cache file
  CACHE_FILE="$HOME/.cache/swww/$CURRENT_MONITOR"

  # Check if the cache file exists for the current monitor output
  if [ -f "$CACHE_FILE" ]; then
    # Get the wallpaper path from the cache file
    WALLPAPER_PATH=$(grep -v 'Lanczos3' "$CACHE_FILE" | head -n 1)
    sleep 1
    swww img "$WALLPAPER_PATH" --transition-type fade --transition-duration 2
  fi
fi
